Merged scenario and portfolio
atlarge-research/opendc pull request #220
Opened 2024-04-19 17:03 UTC by Radu-Nicolae

## Summary
Input is being made from scenario (.json), which further links to topology (.json). Internal codebase adjusted accordingly. Output is done in a simulation results file.

## Implementation Notes :hammer_and_pick:
N/A

## External Dependencies :four_leaf_clover:
N/A

## Breaking API Changes :warning:
Scenario.json file changed (i.e., the input is modified). Portfolio has been deleted, topology, allocation policy, workload, exportModels, failureModels, are now lists.

2024-04-21 19:06 UTC, DanteNiewenhuis approved these changes

2024-04-21 19:07 UTC, DanteNiewenhuis requested changes
Please remove the demo folder from your branch and push it again. 
We don't want any result parquet files to be pushed.

2024-04-22 11:38 UTC, Radu-Nicolae commented
Demo folder removed from git (deleted & untracked). Please review

2024-04-22 11:51 UTC, DanteNiewenhuis approved these changes

2024-04-22 11:51 UTC, merged