Documentation update
atlarge-research/opendc pull request #224
Opened 2024-04-23 17:30 UTC by Radu-Nicolae

## Summary

Documentation update for the changes from PR #220. Added documentation for Scenario in Scenario.md and ScenarioSchema.md.

## Implementation Notes :hammer_and_pick:
N/A

## External Dependencies :four_leaf_clover:
N/A

## Breaking API Changes :warning:
N/A

2024-04-23 19:07 UTC, DanteNiewenhuis requested changes

2024-04-23 19:07 UTC, DanteNiewenhuis commented on site/docs/documentation/Input/ScenarioSchema.md
"name" and "runs" are both not required

2024-04-24 12:05 UTC, Radu-Nicolae commented on site/docs/documentation/Input/ScenarioSchema.md
solved! also, the website runs!

2024-04-24 12:45 UTC, DanteNiewenhuis requested changes

2024-04-24 12:45 UTC, DanteNiewenhuis commented on site/docs/documentation/Input/ScenarioSchema.md
They are both still required in the schema

2024-04-24 13:09 UTC, DanteNiewenhuis approved these changes

2024-04-24 13:09 UTC, merged