Added thermal model for hosts
atlarge-research/opendc pull request #238
Opened 2024-07-27 15:43 UTC by zohaib-c

## Summary

Added the RC Thermal Model to simulate the temperature of hosts.

## Implementation Notes :hammer_and_pick:

* Created a new interface and classes for thermal models.
* Host file now outputs temperature in degrees Celsius.
* Input JSON file now has the option to input a thermal model, otherwise it defaults to the default Intel Xeon 8160 processor's specifications.

2024-07-30 19:05 UTC, DanteNiewenhuis requested changes

2024-07-30 19:05 UTC, DanteNiewenhuis commented on opendc-compute/opendc-compute-service/src/main/java/org/opendc/compute/service/driver/telemetry/HostSystemStats.java
Please rename to cpuTemperature

2024-07-30 19:05 UTC, DanteNiewenhuis commented on opendc-compute/opendc-compute-simulator/src/main/kotlin/org/opendc/compute/simulator/SimHost.kt
Please rename to cpuTemperature

2024-07-30 19:05 UTC, DanteNiewenhuis commented on opendc-compute/opendc-compute-telemetry/src/main/kotlin/org/opendc/compute/telemetry/ComputeMetricReader.kt
Please change all temperature variables to some form of cpuTemperature

2024-07-30 19:05 UTC, DanteNiewenhuis commented on opendc-compute/opendc-compute-telemetry/src/main/kotlin/org/opendc/compute/telemetry/export/parquet/ParquetHostDataWriter.kt
rename to cpu_temperature

2024-07-30 19:05 UTC, DanteNiewenhuis commented on opendc-compute/opendc-compute-topology/src/main/kotlin/org/opendc/compute/topology/specs/TopologySpecs.kt
Please add a comment that states which CPU we are modeling

2024-07-30 19:05 UTC, DanteNiewenhuis commented on opendc-experiments/opendc-experiments-scenario/build.gradle.kts
opendc-experiments-scenario does not exist anymore. So this file should be removed

2024-07-30 19:05 UTC, DanteNiewenhuis commented on opendc-simulator/opendc-simulator-compute/src/main/java/org/opendc/simulator/compute/thermal/ThermalModelFactories.kt
I don't really understand what "rcmodel" and "manifactor" model are

2024-08-10 21:17 UTC, zohaib-c commented on opendc-simulator/opendc-simulator-compute/src/main/java/org/opendc/simulator/compute/thermal/ThermalModelFactories.kt
Added comments to explain what the factories do. Removed manufacturer model for the meantime as it requires refactoring to work with the thermal models class

2024-08-19 08:06 UTC, DanteNiewenhuis approved these changes

2024-08-19 08:14 UTC, DanteNiewenhuis commented on opendc-simulator/opendc-simulator-compute/src/main/java/org/opendc/simulator/compute/SimPsuFactories.java
> +    public static SimPsuFactory simple(CpuPowerModel model, ThermalModel thermalModel) {
Ideally, we would make the thermalModel variable nullable. 
Currently, you always have to put in a thermalModel. 
This is not ideal.

2026-08-31 08:52 UTC, closed without merging